workflows:
  ios-workflow:
    name: iOS Build
    integrations:
      app_store_connect: appstoreapikey   # <- must match EXACT integration name in Codemagic

    environment:
      vars:
        APP_NAME: "shopidubai_app"
        BUNDLE_ID: "com.shopidubai.app"

    scripts:
      - name: Build iOS
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: false
