workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        APP_NAME: "shopidubai_app"
        BUNDLE_ID: "com.shopidubai.app"

    scripts:
      - name: Build iOS
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
        key_id: M2DLCXJP5JZY
        issuer_id: 8965d0c4-e286-4d68-9a6c-cd6a7dcf12d1
        api_key: appstoreapikey
