platform :ios, '13.0'

use_frameworks!
use_modular_headers!

# This is required for Flutter iOS build
flutter_application_path = File.expand_path('..', __dir__)
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
